### ISSUE TITLE
Does Test map in Intruder work?

### ISSUE THREAD

**Issue by RobStorm** [RobStorm/IntruderMapMaker#3]
I'm getting this error: 

`IOException: Failed to Copy File / Directory from 'Assets/Level1.unity' to 'Assets/Level1.unity'.
UnityEditor.FileUtil.ReplaceFile (System.String src, System.String dst) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/editor/FileUtilBindings.gen.cs:67)
Assets.IntruderMM.Editor.ExportLevel.DoWorkToExportScene (System.String myPath, Int32 platIndex) (at Assets/IntruderMM/Editor/ExportLevel.cs:136)
Assets.IntruderMM.Editor.ExportLevel.MultiPlatformExport (System.String myPath) (at Assets/IntruderMM/Editor/ExportLevel.cs:59)
Assets.IntruderMM.Editor.ExportLevel.ExportSceneForIntruderAs () (at Assets/IntruderMM/Editor/ExportLevel.cs:54)
Assets.IntruderMM.Editor.ExportLevel.ExportSceneForIntruder () (at Assets/IntruderMM/Editor/ExportLevel.cs:23)
Assets.IntruderMM.Editor.ExportLevel.PlaySceneInIntruder () (at Assets/IntruderMM/Editor/ExportLevel.cs:299)
Assets.IntruderMM.Editor.ExportLevel.CheckNameAndPlayInIntruder () (at Assets/IntruderMM/Editor/ExportLevel.cs:248)
`

**Comment by RobStorm** [comment]
Testing from there would be fine yeah.

**Comment by justinlueders** [comment]
This is an issue with the game client.  Closing this issue, this will be fixed as part of https://github.com/RobStorm/Intruder/issues/3
